package Management;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author techverse
 */

import java.sql.Connection;
import java.sql.CallableStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;


public class Authentication extends javax.swing.JFrame {

    /**
     * Creates new form Authentication
     */
    public Authentication() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        username_lb = new javax.swing.JLabel();
        userName_lb = new javax.swing.JLabel();
        UserName_txt = new javax.swing.JTextField();
        logIn_bt = new javax.swing.JButton();
        exit_bt = new javax.swing.JButton();
        PassWord_txt = new javax.swing.JPasswordField();
        showPassword = new javax.swing.JCheckBox();
        department_cmx = new javax.swing.JComboBox<>();
        Department_lbl = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("WELCOME TO ELEPHANT HILLS HOTEL RESERVATION SYSTEM.");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        username_lb.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        username_lb.setText("UserName");

        userName_lb.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        userName_lb.setText("PassWord");

        UserName_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserName_txtActionPerformed(evt);
            }
        });

        logIn_bt.setBackground(new java.awt.Color(0, 153, 0));
        logIn_bt.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        logIn_bt.setText("LOG IN");
        logIn_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logIn_btActionPerformed(evt);
            }
        });

        exit_bt.setBackground(new java.awt.Color(204, 0, 0));
        exit_bt.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        exit_bt.setText("EXIT");
        exit_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btActionPerformed(evt);
            }
        });

        showPassword.setText("Show PassWord");
        showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordActionPerformed(evt);
            }
        });

        department_cmx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administration", "Rooms", "Restaurant", "Entertainment" }));

        Department_lbl.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        Department_lbl.setText("Department");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(exit_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(logIn_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(username_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userName_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Department_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(department_cmx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PassWord_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(UserName_txt))
                        .addGap(18, 18, 18)
                        .addComponent(showPassword))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userName_lb, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PassWord_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(showPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(department_cmx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Department_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logIn_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exit_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserName_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserName_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserName_txtActionPerformed

    private void logIn_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logIn_btActionPerformed
          String theDepartment = (String) department_cmx.getSelectedItem();
        String UserName= UserName_txt.getText();
        String password = PassWord_txt.getText();
        String message="";
        if (UserName.isEmpty() || password.isEmpty()) {
           JOptionPane.showMessageDialog(null,"Enter all required details please");
        } 
        else {
            
        
            try {
                try (Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotelreservations","root", "mysql");
                     CallableStatement statement = connection.prepareCall("{CALL TheValidations(?,?,?)}")) {
                    //int EmployeeDigit = Integer.parseInt(EmployeeNum);
                    

                    statement.setString(1, UserName);
                    statement.setString(2, password);
                    statement.setString(3, theDepartment);

                    statement.execute();

                    try (ResultSet resultSet = statement.getResultSet()) {
                        
                        if (resultSet.next()) {
                            message = resultSet.getString("Message");
                            //System.out.println(message); // Display the validation message
                            JOptionPane.showMessageDialog(null, message);
                             
                        }
                        
                    }
                }
            } 
            catch (SQLException e) {
                // Handle database errors (e.g., log or display the error)
               JOptionPane.showMessageDialog(null,"Details Not Found");
            }
        
        if (message.equals("Log in SUCCESSFUL")) {
                                this.dispose(); // Close the login window
                switch (theDepartment) {
                    case "Administration":
                        new Home().setVisible(true); // Show another window
                        break;
                    case "Rooms":
                        new rooms().setVisible(true);
                        break;
                    case "Restaurant":
                        new restaurant().setVisible(true);
                        break;
                    case "Entertainment": 
                        new Entertainment().setVisible(true);
                        break;
                    default:
                        JOptionPane.showMessageDialog(null,"Incorrect Credentials!!","Log In Details",JOptionPane.ERROR_MESSAGE);
                        break;
                }
        }                
    }
        System.out.println(UserName);
        System.out.println(password);
        System.out.println(theDepartment);
        
    
        // TODO add your handling code here:
    }//GEN-LAST:event_logIn_btActionPerformed

    private void exit_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btActionPerformed
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_exit_btActionPerformed

    private void showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordActionPerformed
        if(showPassword.isSelected()) {
            PassWord_txt.setEchoChar((char)0);
        }
         else {
             PassWord_txt.setEchoChar('*');
         }
        // TODO add your handling code here:
    }//GEN-LAST:event_showPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Authentication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Authentication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Authentication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Authentication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Authentication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Department_lbl;
    private javax.swing.JPasswordField PassWord_txt;
    private javax.swing.JTextField UserName_txt;
    private javax.swing.JComboBox<String> department_cmx;
    private javax.swing.JButton exit_bt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logIn_bt;
    private javax.swing.JCheckBox showPassword;
    private javax.swing.JLabel userName_lb;
    private javax.swing.JLabel username_lb;
    // End of variables declaration//GEN-END:variables
}
