/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Management;

/**
 *
 * @author Tangeni Matheus
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
        //this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Restaurant_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        EntertainmentArea_btn = new javax.swing.JButton();
        Rooms_btn = new javax.swing.JButton();
        AccountsManagement_btn = new javax.swing.JButton();
        Exit_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Restaurant_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Restaurant_btn.setText("RESTAURANT");
        Restaurant_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Restaurant_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Restaurant_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 230, 40));

        jLabel2.setFont(new java.awt.Font("Bernard MT Condensed", 2, 18)); // NOI18N
        jLabel2.setText("WELCOME  TO ELEPHANT HILLS HOTEL RESERVATION SYSTEM.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 410, -1));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel3.setText("Which services do you want to manage ?");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        EntertainmentArea_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EntertainmentArea_btn.setText(" VENUES");
        EntertainmentArea_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntertainmentArea_btnActionPerformed(evt);
            }
        });
        jPanel1.add(EntertainmentArea_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 230, 40));

        Rooms_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Rooms_btn.setText("ROOMS");
        Rooms_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rooms_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Rooms_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 230, 40));

        AccountsManagement_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AccountsManagement_btn.setText("USER ACCOUNTS");
        AccountsManagement_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountsManagement_btnActionPerformed(evt);
            }
        });
        jPanel1.add(AccountsManagement_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 230, 40));

        Exit_btn.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        Exit_btn.setText("EXIT");
        Exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Exit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Restaurant_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Restaurant_btnActionPerformed
        // TODO add your handling code here:
        restaurantAdmin restaurantPage = new restaurantAdmin();
        restaurantPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Restaurant_btnActionPerformed

    private void Rooms_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rooms_btnActionPerformed
        // TODO add your handling code here:
        roomsAdmin roomsPage = new roomsAdmin();
        roomsPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Rooms_btnActionPerformed

    private void EntertainmentArea_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntertainmentArea_btnActionPerformed
        // TODO add your handling code here:
        EntertainmentAdmin entertainmentPage = new EntertainmentAdmin();
        entertainmentPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EntertainmentArea_btnActionPerformed

    private void AccountsManagement_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountsManagement_btnActionPerformed
        UserAccounts AccountsWindow=new UserAccounts();
        AccountsWindow.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_AccountsManagement_btnActionPerformed

    private void Exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_btnActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_Exit_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccountsManagement_btn;
    private javax.swing.JButton EntertainmentArea_btn;
    private javax.swing.JButton Exit_btn;
    private javax.swing.JButton Restaurant_btn;
    private javax.swing.JButton Rooms_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
