
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class Entertainment extends javax.swing.JFrame {
 


    /**
     * Creates new form Entertainment
     */
    public Entertainment() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblMethod = new javax.swing.JLabel();
        jlblContactDetails = new javax.swing.JLabel();
        jlblDate = new javax.swing.JLabel();
        jlblEntertainment = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        contactNamber = new javax.swing.JTextField();
        methodOfPayment = new javax.swing.JComboBox<>();
        entertainment = new javax.swing.JComboBox<>();
        Back_btn = new javax.swing.JButton();
        Reserve_btn = new javax.swing.JButton();
        fullName = new javax.swing.JTextField();
        jlblName4 = new javax.swing.JLabel();
        jlblName3 = new javax.swing.JLabel();
        emailAdress = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblMethod.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jlblMethod.setText("METHOD OF PAYMENT");
        jPanel1.add(jlblMethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 240, 40));

        jlblContactDetails.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jlblContactDetails.setText("CONTACT NUMBER");
        jPanel1.add(jlblContactDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 190, 40));

        jlblDate.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jlblDate.setText("DATE");
        jPanel1.add(jlblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 190, 40));

        jlblEntertainment.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jlblEntertainment.setText("ENTERTAINMENT");
        jPanel1.add(jlblEntertainment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 190, 40));

        date.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 240, 30));

        contactNamber.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        contactNamber.setText("+264 ");
        contactNamber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactNamberActionPerformed(evt);
            }
        });
        jPanel1.add(contactNamber, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 240, 30));

        methodOfPayment.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        methodOfPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CASH", "VISA" }));
        jPanel1.add(methodOfPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 240, -1));

        entertainment.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        entertainment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HALL PINA", "CONFERENCE ROOM 707", "POOL AREA" }));
        entertainment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entertainmentActionPerformed(evt);
            }
        });
        jPanel1.add(entertainment, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 240, -1));

        Back_btn.setBackground(new java.awt.Color(255, 0, 0));
        Back_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Back_btn.setText("BACK");
        Back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 130, 30));

        Reserve_btn.setBackground(new java.awt.Color(51, 204, 0));
        Reserve_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Reserve_btn.setText("RESERVE");
        Reserve_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reserve_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Reserve_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 120, 30));

        fullName.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        fullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullNameActionPerformed(evt);
            }
        });
        jPanel1.add(fullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 240, 30));

        jlblName4.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jlblName4.setText("FULL NAME");
        jPanel1.add(jlblName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 190, 40));

        jlblName3.setBackground(new java.awt.Color(255, 255, 255));
        jlblName3.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jlblName3.setText("EMAIL ADRESS");
        jPanel1.add(jlblName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 190, 40));

        emailAdress.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        emailAdress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailAdressActionPerformed(evt);
            }
        });
        jPanel1.add(emailAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 240, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 600, 440));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 680, 450));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BOOK A VENUE");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 640, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailAdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailAdressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailAdressActionPerformed

    private void contactNamberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactNamberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactNamberActionPerformed

    private void Back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_btnActionPerformed
        // TODO add your handling code here:
        EntertainmentDetails entertainment=new EntertainmentDetails();
        this.dispose();
        entertainment.setVisible(true);
    }//GEN-LAST:event_Back_btnActionPerformed

    private void entertainmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entertainmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entertainmentActionPerformed

    private void Reserve_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reserve_btnActionPerformed
         // TODO add your handling code here:
     // TODO add your handling code here:
    String fullNameText = fullName.getText();
    String emailText = emailAdress.getText();
    String contactNumberText = contactNamber.getText();
    String dateText = date.getText();
    String entertainmentText = (String) entertainment.getSelectedItem();
    String methodOfPaymentText = (String) methodOfPayment.getSelectedItem();

    if (fullNameText.isEmpty() || emailText.isEmpty() || contactNumberText.isEmpty() || dateText.isEmpty() || entertainmentText.isEmpty() || methodOfPaymentText.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please Fill In All The Fields", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    int atIndex = emailText.indexOf("@");
    int dotIndex = emailText.lastIndexOf(".");
    if (!isValidDate(dateText)) {
        JOptionPane.showMessageDialog(null, "Invalid Date Format. Please use DD/MM/YYYY", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (!isFutureDate(dateText)) {
        JOptionPane.showMessageDialog(null, "The Date You Entered Is In The Past", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (atIndex <= 0 || dotIndex <= atIndex || dotIndex == emailText.length() - 1) {
        JOptionPane.showMessageDialog(null, "Invalid Email Address Format", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }


    try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/HotelReservations", "root", "mysql");
        CallableStatement stmt = conn.prepareCall("{call EntertainmentReservation(?, ?, ?, ?, ?, ?)}");
        stmt.setString(1, fullNameText);
        stmt.setString(2, emailText);
        stmt.setString(3, contactNumberText);
        stmt.setString(4, dateText);
        stmt.setString(5, entertainmentText);
        stmt.setString(6, methodOfPaymentText);
        stmt.executeUpdate();
        JOptionPane.showMessageDialog(null, "Reservation Successful", "Success", JOptionPane.INFORMATION_MESSAGE);
    } 
    catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error Submitting Reservation: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
        
    }//GEN-LAST:event_Reserve_btnActionPerformed

    private void fullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entertainment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entertainment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entertainment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entertainment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entertainment().setVisible(true);
            }
        });
    }
    private boolean isValidDate(String date) {
        String datePattern = "^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[012])/(\\d{4})$";
        Pattern pattern = Pattern.compile(datePattern);
        Matcher matcher = pattern.matcher(date);
        return matcher.matches();
}
    private boolean isFutureDate(String date) {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate enteredDate = LocalDate.parse(date, formatter);
        LocalDate currentDate = LocalDate.now();
        return enteredDate.isAfter(currentDate) || enteredDate.equals(currentDate);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_btn;
    private javax.swing.JButton Reserve_btn;
    private javax.swing.JTextField contactNamber;
    private javax.swing.JTextField date;
    private javax.swing.JTextField emailAdress;
    private javax.swing.JComboBox<String> entertainment;
    private javax.swing.JTextField fullName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlblContactDetails;
    private javax.swing.JLabel jlblDate;
    private javax.swing.JLabel jlblEntertainment;
    private javax.swing.JLabel jlblMethod;
    private javax.swing.JLabel jlblName3;
    private javax.swing.JLabel jlblName4;
    private javax.swing.JComboBox<String> methodOfPayment;
    // End of variables declaration//GEN-END:variables
}
