/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class MainServices extends javax.swing.JFrame {

    /**
     * Creates new form MainServices
     */
    public MainServices() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Restaurant_btn = new javax.swing.JButton();
        Rooms_btn = new javax.swing.JButton();
        EntertainmentArea_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        exit_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Restaurant_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Restaurant_btn.setText("RESTAURANT");
        Restaurant_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Restaurant_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Restaurant_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 260, 40));

        Rooms_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Rooms_btn.setText("ROOMS");
        Rooms_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rooms_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Rooms_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 260, 40));

        EntertainmentArea_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EntertainmentArea_btn.setText("ENTERTAINMENT VENUES");
        EntertainmentArea_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntertainmentArea_btnActionPerformed(evt);
            }
        });
        jPanel1.add(EntertainmentArea_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 260, 40));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel3.setText("Which services do you want to reserve for ?");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel2.setText("WELCOME TO ELEPHANT HILLS HOTEL RESERVATION SYSTEM.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 420, 40));

        exit_btn.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        exit_btn.setText("EXIT");
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });
        jPanel1.add(exit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 110, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 630, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EntertainmentArea_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntertainmentArea_btnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        EntertainmentDetails entertainmentPage = new EntertainmentDetails();
        entertainmentPage.setVisible(true);
    }//GEN-LAST:event_EntertainmentArea_btnActionPerformed

    private void Rooms_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rooms_btnActionPerformed
        // TODO add your handling code here:
        roomsDetails roomsPage = new roomsDetails();
        roomsPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Rooms_btnActionPerformed

    private void Restaurant_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Restaurant_btnActionPerformed
        // TODO add your handling code here:
        restaurantDetails restaurantPage1 = new restaurantDetails();
        restaurantPage1.setVisible(true);
    }//GEN-LAST:event_Restaurant_btnActionPerformed

    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_exit_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainServices().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EntertainmentArea_btn;
    private javax.swing.JButton Restaurant_btn;
    private javax.swing.JButton Rooms_btn;
    private javax.swing.JButton exit_btn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
