import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class Restaurant extends javax.swing.JFrame {
    



    /**
     * Creates new form Restaurant
     */
    public Restaurant() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblName = new javax.swing.JLabel();
        fullName = new javax.swing.JTextField();
        jlblDate = new javax.swing.JLabel();
        jlblTableNumber = new javax.swing.JLabel();
        tableNumber = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jbtnReserve = new javax.swing.JButton();
        Cancel_btn = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jlblPaymentMethod = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jlblDate1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblName.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jlblName.setText("FULL NAME");
        jPanel1.add(jlblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 160, 30));

        fullName.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jPanel1.add(fullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 160, 30));

        jlblDate.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jlblDate.setText("DATE");
        jPanel1.add(jlblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 90, 40));

        jlblTableNumber.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jlblTableNumber.setText("TABLE NUMBER");
        jPanel1.add(jlblTableNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 170, 40));

        tableNumber.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        tableNumber.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        tableNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableNumberActionPerformed(evt);
            }
        });
        jPanel1.add(tableNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 160, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel1.setText("SERVICE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 170, 30));

        jComboBox2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BREAKFAST", "DINNER", "LUNCH", "DESSERT" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 160, -1));

        jbtnReserve.setBackground(new java.awt.Color(0, 204, 0));
        jbtnReserve.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnReserve.setText("RESERVE");
        jbtnReserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReserveActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnReserve, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 150, 40));

        Cancel_btn.setBackground(new java.awt.Color(255, 0, 0));
        Cancel_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Cancel_btn.setText("BACK");
        Cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Cancel_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 160, 40));

        jComboBox3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CASH", "VISA" }));
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 160, 30));

        jlblPaymentMethod.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jlblPaymentMethod.setText("PAYMENT METHOD");
        jPanel1.add(jlblPaymentMethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 210, 30));

        date.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 160, 30));

        email.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 160, 30));

        jlblDate1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jlblDate1.setText("EMAIL");
        jPanel1.add(jlblDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 630, 440));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 740, 520));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MAKE A RESERVATION");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 640, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tableNumberActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jbtnReserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReserveActionPerformed
        // TODO add your handling code here:
    String fullNameValue = fullName.getText();
    String dateString = date.getText();
    String emailAddressValue = email.getText();
    int tableNumberValue = Integer.parseInt(tableNumber.getSelectedItem().toString());
    String chosenServiceValue = jComboBox2.getSelectedItem().toString();
    String chosenPaymentMethodValue = jComboBox3.getSelectedItem().toString();
    
    if (fullNameValue.isEmpty() || dateString.isEmpty() || emailAddressValue.isEmpty() || tableNumberValue==0) {
        JOptionPane.showMessageDialog(null, "Please Fill In All The Fields", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
     int atIndex = emailAddressValue.indexOf("@");
    int dotIndex = emailAddressValue.lastIndexOf(".");
    
    if (!isValidDate(dateString)) {
        JOptionPane.showMessageDialog(null, "Invalid Date Format. Please use dd/mm/yyyy", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (!isFutureDate(dateString)) {
        JOptionPane.showMessageDialog(null, "The Date You Entered Is In The Past", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (atIndex <= 0 || dotIndex <= atIndex || dotIndex == emailAddressValue.length() - 1) {
        JOptionPane.showMessageDialog(null, "Invalid Email Address Format", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Call the stored procedure to insert the reservation
    try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/HotelReservations", "root", "mysql");
        CallableStatement cstmt = conn.prepareCall("{call InsertRestaurantReservation(?, ?, ?, ?, ?, ?)}");
        cstmt.setString(1, fullNameValue);
        cstmt.setString(2, dateString);
        cstmt.setString(3, emailAddressValue);
        cstmt.setInt(4, tableNumberValue);
        cstmt.setString(5, chosenServiceValue);
        cstmt.setString(6, chosenPaymentMethodValue);
        cstmt.executeUpdate();
        JOptionPane.showMessageDialog(this, "Reservation Successful");
        conn.close();
    } 
    catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error Submitting The Reservation: " + e.getMessage());
    }
    
    }//GEN-LAST:event_jbtnReserveActionPerformed

    private void Cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel_btnActionPerformed
        // TODO add your handling code here:
        restaurantDetails restaurant=new restaurantDetails();
        this.dispose();
        restaurant.setVisible(true);
        
    }//GEN-LAST:event_Cancel_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Restaurant().setVisible(true);
            }
        });
    }
    private boolean isValidDate(String date) {
        String regex = "^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[012])/(\\d{4})$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(date);
        return matcher.matches();
}
    private boolean isFutureDate(String date) {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate enteredDate = LocalDate.parse(date, formatter);
        LocalDate currentDate = LocalDate.now();
        return enteredDate.isAfter(currentDate) || enteredDate.equals(currentDate);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel_btn;
    private javax.swing.JTextField date;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fullName;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnReserve;
    private javax.swing.JLabel jlblDate;
    private javax.swing.JLabel jlblDate1;
    private javax.swing.JLabel jlblName;
    private javax.swing.JLabel jlblPaymentMethod;
    private javax.swing.JLabel jlblTableNumber;
    private javax.swing.JComboBox<String> tableNumber;
    // End of variables declaration//GEN-END:variables
}
